// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2DbK2E47w8QuUHxvbWBqM7CBFpCWKUXY',
    appId: '1:631344061445:web:ab16d31eb95d751200d06c',
    messagingSenderId: '631344061445',
    projectId: 'zdeliver-acc55',
    authDomain: 'zdeliver-acc55.firebaseapp.com',
    storageBucket: 'zdeliver-acc55.firebasestorage.app',
    measurementId: 'G-1EVQ487PDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLr0f-78O3_7ZggukjT_xKh5BxPZ-cTv0',
    appId: '1:631344061445:android:b729dd9c8b0f6b1400d06c',
    messagingSenderId: '631344061445',
    projectId: 'zdeliver-acc55',
    storageBucket: 'zdeliver-acc55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaoIZ4kBDBc-x1k4TJuNOA7Q19-oaY-K0',
    appId: '1:631344061445:ios:99045d3ee596369a00d06c',
    messagingSenderId: '631344061445',
    projectId: 'zdeliver-acc55',
    storageBucket: 'zdeliver-acc55.firebasestorage.app',
    iosBundleId: 'com.example.mrsgorilla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaoIZ4kBDBc-x1k4TJuNOA7Q19-oaY-K0',
    appId: '1:631344061445:ios:99045d3ee596369a00d06c',
    messagingSenderId: '631344061445',
    projectId: 'zdeliver-acc55',
    storageBucket: 'zdeliver-acc55.firebasestorage.app',
    iosBundleId: 'com.example.mrsgorilla',
  );
}
